#!/usr/bin/env python


import sys, os #, shutil, subprocess
import argparse
import up

from yapsy.PluginManager import PluginManager

__author__ = 'Maxime Haineault'

parser = argparse.ArgumentParser(prog='up', description='Deploy shit up the Internet')
parser.add_argument('-l', '--log-level', default=0, help='Log level', required=False)

def run():
    pm = PluginManager()
    pm.setPluginPlaces([
        os.path.join(os.path.dirname(up.__file__), 'plugins'),
    ])

    pm.collectPlugins()
    subparsers = parser.add_subparsers(dest='command', help="test subparser")

    # Activate all loaded plugins
    for plugin in pm.getAllPlugins():
        pm.activatePluginByName(plugin.name)
        obj = plugin.plugin_object
        # Bind sub commands if needed
        if hasattr(obj, 'argparse'):
            obj.argparse(subparsers)
        if hasattr(obj, 'init'):
            obj.init()

    args = parser.parse_args()
    return 0


def main():
    sys.exit(run())

if __name__=='__main__':
    main()
